export type TwilioGetTwimlParameters = {
  Called: string;
  ToState: string;
  CallerCountry: string;
  Direction: 'outbound-api' | 'inbound';
  CallerState: string;
  ToZip: string;
  StirStatus: string;
  CallSid: string;
  To: string;
  CallerZip: string;
  ToCountry: string;
  StirVerstat: string;
  CalledZip: string;
  ApiVersion: string;
  CalledCity: string;
  CallStatus: string;
  From: string;
  AccountSid: string;
  CalledCountry: string;
  CallerCity: string;
  ToCity: string;
  FromCountry: string;
  Caller: string;
  FromCity: string;
  CalledState: string;
  FromZip: string;
  FromState: string;
};
